#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EncyclopedieWakfu.Resource", IsApplication=true)]

namespace EncyclopedieWakfu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgroundMain = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BestiaireIcone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ClassIcone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int JobsIcone = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int MainContentLayout = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int buttonBestaire = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int buttonClasse = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int buttonJobs = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int classdescription = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int classdescriptiontitle = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int classname = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int classspelltitle = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int gridLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int passifspell = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int spellgrid = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClassView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
